name: erp_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.2
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  dropdown_search: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/

